CREATE TABLE Team_List(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(50), SPOC_ID INT);

create table users(ID INT  PRIMARY KEY AUTO_INCREMENT, EMAIL VARCHAR(256)
, PASSWORD VARCHAR(256), ROLE VARCHAR(10), COLLEGE VARCHAR(100));